### ISSUE TITLE
[Bug] Update turn on pages instructions

### ISSUE THREAD

**Issue by sebbrandes** [skills/github-pages#10]
**Update of the content of Step 1**

Actually, the indications are : 
3.Click **Pages**, in the "GitHub Pages" section, use the Source drop-down, then select **main branch**.

But when you look on the site, it is more like :

![image](https://user-images.githubusercontent.com/110712939/183256225-be0e19c0-4a11-4741-ace5-c342626c6d4e.png)

3.Click **Pages**, in the "Code and automation" section, use the Branch drop-down, then select **main**

**Comment by Lastrick1** [comment]
Agree with @sebbrandes on this issue, this instruction is poorly worded. I would expand on what OP said by adding something like, 

"3. Click **Pages** in the "Code and automation" section. Next, ensure the Source is set to "Deploy from a branch"; then using the Branch drop-down, select **main**."

**Comment by naturecomplexion** [comment]
https://www.naturecomplexion.com
