### ISSUE TITLE
Need help completing transfer of Crypto

### ISSUE THREAD

**Issue by kbtolbert** [skills/github-pages#118]
### Summary

A clear and concise description of what the bug is, and what you expected to happen.

### How to reproduce

2. Click on '...'
3. Scroll down to '...'

Please include screenshots.

**Comment by 72158895omar1** [comment]
Omar

**Comment by 72158895omar1** [comment]
Confirma omar

**Comment by 72158895omar1** [comment]
Confirmo omar
