### ISSUE TITLE
Request Git: histo664

### ISSUE THREAD

**Issue by histo664** [skills/github-pages#199]
### KYC Using Your GitHub Account
Please make sure your GitHub account meets the following requirements (all are required):
- [] The issue title must be: Request GitHub KYC - Your US.KG Panel registered your registered username. (For example, your title should be: **Request Git"
- [] This is not a new GitHub account, it has existing repositories and sta
- [x] This is my first US.KG NIC Panel account.
- [] I promise not to use the domain name for criminal or abusive
- [] Please star this repository, This will let more people know
orname. This ensures our automated script can detect
‹ample**)
**Your Account Details (US.KG NIC Panel):**
Please fill out the following information; otherwise, your request will not be processed:
- Username: histo664
- Reason for Registering the .US.KG Domain Name (Why):building a blog

**Comment by suraj511** [comment]
1. Set the Issue Title
Open the appropriate GitHub repository for KYC requests.
Create a new issue.
Use the required issue title format:
mathematica
Copy code

Request GitHub KYC - Your US.KG Panel registered username

Example:---Request GitHub KYC - histo664

**Comment by suraj511** [comment]
2. Ensure Your GitHub Account Meets the Requirements
Existing Account: Make sure your GitHub account is not newly created and contains existing repositories and stars.
Public Profile: Ensure that your repositories and account activity are visible for verification.
Star the Repository: Star the GitHub repository where you're submitting the KYC request. (Locate the star button at the top-right of the repository page.)


3. Submit the Required Details in the Issue
Fill out the details in the issue body exactly as required. Example:

Your Account Details (US.KG NIC Panel):
Username: histo664
Reason for Registering the .US.KG Domain Name (Why): building a blog

4. Promise Compliance
Include the following statement in your issue body:
css
Copy code

I promise not to use the domain name for criminal or abusive purposes.
