### ISSUE TITLE
Github Pages tutorial creates some confusions for beginners

### ISSUE THREAD

**Issue by dkrasne** [skills/github-pages#57]
### Discussed in https://github.com/orgs/skills/discussions/105
See below for some things that need to be fixed in the tutorial instructions for GitHub Pages.

<div type='discussions-op-text'>

<sup>Originally posted by **dkrasne** October 30, 2022</sup>
Here are a few hitches I ran into while setting up GitHub Pages from the tutorial:

1. Under 'how to start this course,' the screenshot is from introduction-to-github, not github-pages. It's not clear whether one should choose the name of one's future blog address, or if it makes sense to leave the default name of github-pages. This should be clarified.
2. Step 1, instruction 3 ("Click Pages, in the "GitHub Pages" section, use the Source drop-down, then select main branch.") did not match exactly what I saw. 'Main branch' was not an option under the Source drop-down; the only option other than GitHub Actions was "Deploy from a Branch". The **SECOND** drop-down menu (under Branch, not Source) gave "main" as an option.
3. I'm concerned that because of one or both of these unclear instructions, I did something wrong at some point, because when I go to my new page (currently at https://dkrasne.github.io/github-pages/ although I plan to rename it if I can't figure this out), the bottom of the page reads: "github-pages" and "Lesson on building a blog with Jekyll". So I think I _must_ have done something wrong (especially since I had to search for the button to merge the pull request, it didn't show up automatically), but I can't figure out where, since I followed all of the subsequent instructions precisely.
4. Even if I actually did everything correctly, those two unclear instructions should be changed, for the sake of beginners.

Help would be appreciated, thanks!
</div>

**Comment by sinsukehlab** [comment]
Hitch 2 (about GitHub Pages drop-down menu) is resolved in #18.

**Comment by hectorsector** [comment]
Thanks for the feedback! This issue is rather stale now, and we've seen some updates to the course since then. I am closing it out, but if you're still having issues please do not hesitate to open a new issue for each problem.
