### ISSUE TITLE
[Bug] github page link is never mentioned or explained here

### ISSUE THREAD

**Issue by jahway603** [skills/github-pages#73]
After following this skill-builder, the github page link is never mentioned or explained here so the user has no clue where they need to navigate to...

https://USERNAME.github.io/skills-github-pages/

**Comment by Vue-Pu** [comment]
#76

**Comment by sinsukehlab** [comment]
The GitHub Pages site link is explained in Step 1.
1. Wait about _one minute_ then refresh this page (the one you're following instructions from). [GitHub Actions](https://docs.github.com/en/actions) will automatically update to the next step.
   > Turning on GitHub Pages creates a deployment of your repository. GitHub Actions may take up to a minute to respond while waiting for the deployment. Future steps will be about 20 seconds; this step is slower.
   > **Note**: In the **Pages** of **Settings**, the **Visit site** button will appear at the top. Click the button to see your GitHub Pages site.

**Comment by hectorsector** [comment]
https://github.com/skills/github-pages/issues/73
