### ISSUE TITLE
[Feature] Step 5 refers the learner to Step 2

### ISSUE THREAD

**Issue by sinsukehlab** [skills/github-pages#85]
### Summary

Step 5 refers the learner to Step 2 when the PR is not opened, but Step 2 won't be shown in README.md.

### Changes

Provide a link to Step 2 in Step 5.

**Comment by sinsukehlab** [comment]
I mean that some learners who have skipped the optional task in Step 2 might want to read 2-configure-your-site.md in the final step.

**Comment by hectorsector** [comment]
Thanks for clarifying, since I flagged the PR for a content reviewer, I'll let them chime in!
